apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-mits
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-mits
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-mits
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-mits
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-mits
    spec:
      containers:
      - image: quay.io/qijing/happy-path-uiwj-tenant/appstudio/dc-metro-map-mits@sha256:b3bdf2c649c653920bf7eeb9953f2693b39a3b250817f5f381d36ec74478c02c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
